blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://wordpress.org/support/plugin/adventure-treks/
    about: Ask usage questions on the WordPress.org support forum.
